server:
  port: 8001
spring:
  application:
    name: service-hystrix-provider
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka701.com:7001/eureka
  instance:
    instance-id: hystrix-service-8001
    prefer-ip-address: true
