server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuzeshun/springCloud.git #Github上面的git仓库名字
          ####搜索目录
          search-paths:
            - springCloud
      ####读取分支
      label: main

#rabbitmq配置
  rabbitmq:
    port: 5672
    password: guest
    host: localhost
    username: guest


management: #暴露bus刷新端口
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: bus-refresh


#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka701.com:7001/eureka
