server:
  port: 80

spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率，一般鉴于0到1之间

eureka:
  client:
    service-url:
      defaultZone: http://eureka701.com:7001/eureka/,http://eureka702.com:7002/eureka/
    fetch-registry: true
