server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行
      routes:
        - id: toute1 #路由ID，没有固定规则但要求要唯一，建议配合事务名
#          uri: http://localhost:8001 #匹配后服务提供的路由地址
          uri: lb://payment-server-provider #
          predicates:
            - Path=/get/** #断言，也就是匹配条件，路径相匹配的进行路由

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka701.com:7001/eureka