server:
  port: 80

spring:
  application:
    name: cloud-server-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}