server:
  port: 80

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      default-binder: rabbit # 设置要绑定的消息服务的具体设置
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          binder: rabbit

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka701.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: consumer-80.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址
